<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://support.ics.uci.edu/laptops
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://intranet.ics.uci.edu
<class 'AttributeError'> 'NoneType' object has no attribute 'content' http://cocoa-krispies.ics.uci.edu/~paolo/JuliusC
<class 'AttributeError'> 'NoneType' object has no attribute 'content' http://http://www.informatics.uci.edu
<class 'ValueError'> Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' http://malek.ics.uci.edu
<class 'ValueError'> Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' http://hana.ics.uci.edu/Gary_vita
<class 'ValueError'> Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
<class 'ValueError'> Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://jgarcia.ics.uci.edu
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' http://hana.ics.uci.edu/wizard
<class 'AttributeError'> 'NoneType' object has no attribute 'content' http://soc.ics.uci.edu
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://helpdesk.ics.uci.edu/Ticket/Display.html?id=69288
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://support.ics.uci.edu/laptops
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://intranet.ics.uci.edu
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://support.ics.uci.edu/laptops
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://intranet.ics.uci.edu
<class 'AttributeError'> 'NoneType' object has no attribute 'content' http://cocoa-krispies.ics.uci.edu/~paolo/JuliusC
<class 'AttributeError'> 'NoneType' object has no attribute 'content' http://http://www.informatics.uci.edu
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://support.ics.uci.edu/laptops
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://intranet.ics.uci.edu
<class 'UnicodeDecodeError'> 'utf-8' codec can't decode byte 0xa0 in position 43615: invalid start byte
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://support.ics.uci.edu/laptops
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://support.ics.uci.edu/laptops/index.php
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://support.ics.uci.edu/laptops/index.php?r=site/login
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://support.ics.uci.edu/laptops/index.php?r=site/index
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://intranet.ics.uci.edu
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' https://intranet.ics.uci.edu/index.phtml?topic=%3CBIG%3EPlease+login%21%3C%2FBIG%3E%0A&state__=wcapp.help%2F%2F1580546650%2F%2F%2F%2F%2F%26f91bd3ea686cff813339674c84e0087d
<class 'AttributeError'> 'NoneType' object has no attribute 'content' http://luci.ics.uci.edu
<class 'AttributeError'> 'NoneType' object has no attribute 'delay' http://cert.ics.uci.edu
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773080>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/visual-tweets
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157809b0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/communication
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771e48>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/photos
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e6518>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/mobile-photos
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9320>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/instagram
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157733c8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/mchron
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ab38>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/lifelog
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a940>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/computervision-multimedia
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9908>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/search-research-compute-vision-multimedia
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771128>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/computer-vision-multimedia
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771898>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/tag/university-business-knowledge
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773c88>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/category/prospecting-information
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773320>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/category/personal
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ac18>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/category/entrepreneurism
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a0b8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/category/experiential-computing
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156db438>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/category/general-updates
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157719b0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/diversity-and-india
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773400>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/category/technical-thoughts
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773898>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/author/ramesh
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ae48>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/personal/favorite-quotes
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a048>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/personal/favorite-books
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9940>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/personal/education
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f93c8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/personal/past-affiliations
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9d30>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/personal
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773470>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/professionalsocial/interviews
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773400>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/professionalsocial/recognitions
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771908>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/professionalsocial/services
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e2cf8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/professionalsocial
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578afd0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/partners/collaborators
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a4a8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/partners/past-students
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115694be0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/partners/current-students
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771e80>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/partners
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157732e8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/entrepreneurship/past-companies
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157735c0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/entrepreneurship/current-companies
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a7f0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/entrepreneurship
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a470>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/teaching/past-courses
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9f28>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/teaching/current-courses
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115786470>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/teaching
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773da0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research/research-papers/multimedia-information-management
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773ba8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research/research-papers/experiential-computing
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e2f60>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research/research-papers/computer-vision
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157716d8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research/research-papers
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115780e48>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research/projects
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a4e0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research/presentations
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578aa20>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research/patents
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157809b0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research/books
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771dd8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/research
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e2f60>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/blog
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773cf8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/about-ramesh/events
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9ef0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/about-ramesh/news
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771160>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/~cs223
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fgrape.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771780>: Failed to establish a new connection: [Errno 61] Connection refused')) https://grape.ics.uci.edu/wiki/public/wiki/cs222-2018-fall
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115780e48>: Failed to establish a new connection: [Errno 61] Connection refused')) https://ngs.ics.uci.edu/teaching/fall08/Multimedia
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=http%3A%2F%2Fngs.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9320>: Failed to establish a new connection: [Errno 61] Connection refused')) http://ngs.ics.uci.edu
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a940>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/~ics143
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ae10>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/~nalini
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=http%3A%2F%2Fchenli.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156948d0>: Failed to establish a new connection: [Errno 61] Connection refused')) http://chenli.ics.uci.edu
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fgrape.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771f98>: Failed to establish a new connection: [Errno 61] Connection refused')) https://grape.ics.uci.edu/wiki/asterix/wiki/cs122a-2018-spring
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773ac8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/~mjcarey
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fisg.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157730b8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://isg.ics.uci.edu/publications
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fisg.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f98d0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://isg.ics.uci.edu/projects
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fisg.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a470>: Failed to establish a new connection: [Errno 61] Connection refused')) https://isg.ics.uci.edu/visitors
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fisg.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a7b8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://isg.ics.uci.edu/research_staff
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fisg.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157980f0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://isg.ics.uci.edu/alumni
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fisg.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157710f0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://isg.ics.uci.edu/students
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fisg.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a320>: Failed to establish a new connection: [Errno 61] Connection refused')) https://isg.ics.uci.edu/people/faculty
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=http%3A%2F%2Ffr.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a1d0>: Failed to establish a new connection: [Errno 61] Connection refused')) http://fr.ics.uci.edu/haiti
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=http%3A%2F%2Ffr.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9358>: Failed to establish a new connection: [Errno 61] Connection refused')) http://fr.ics.uci.edu
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=http%3A%2F%2Fcert.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157731d0>: Failed to establish a new connection: [Errno 61] Connection refused')) http://cert.ics.uci.edu/SAFIRE
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fnalini.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773cf8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://nalini.ics.uci.edu/contact-info
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fnalini.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f33c8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://nalini.ics.uci.edu/professional-activities
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fnalini.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773be0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://nalini.ics.uci.edu/awards
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fnalini.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773438>: Failed to establish a new connection: [Errno 61] Connection refused')) https://nalini.ics.uci.edu/teaching
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fnalini.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771438>: Failed to establish a new connection: [Errno 61] Connection refused')) https://nalini.ics.uci.edu/about
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771630>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/~dsm/publications.html
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fisg.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9198>: Failed to establish a new connection: [Errno 61] Connection refused')) https://isg.ics.uci.edu
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ab70>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/~dsm
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fnalini.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a828>: Failed to establish a new connection: [Errno 61] Connection refused')) https://nalini.ics.uci.edu/research
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a470>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/~sharad
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9b00>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1270
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=http%3A%2F%2Ftippersweb.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9780>: Failed to establish a new connection: [Errno 61] Connection refused')) http://tippersweb.ics.uci.edu
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771278>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1187
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771978>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news.php?id=1688
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157732b0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773358>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/employment/employ_faculty.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11576b3c8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/employment
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773208>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1690
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771c88>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1693
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771be0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1694
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9320>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1695
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9eb8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1696
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a8d0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1697
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ada0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1671
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e2a20>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1683
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771dd8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/view_news?id=1687
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f3898>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/events/competition
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.informatics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773358>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.informatics.uci.edu/support/provide-projects
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a710>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/involved/corporate_partner
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11576b278>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/involved/leadership_council
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11576bac8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/alumni
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773128>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/involved
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156a35c0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/annualreport
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771fd0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news/press
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e6160>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/social
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fcalendar.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e2cf8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://calendar.ics.uci.edu/calendar.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f96a0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/news
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11576bcf8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/search/search_graduate_all.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e6518>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/search/index.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771898>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/faculty
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104300390>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/search
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773b38>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/community/scholarships/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a710>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/sao/SAO_Events.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11576be48>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/resources/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115766160>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/QA_Graduation
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773710>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/policies/CS199_IN4MATX199
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773b38>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/policies/Withdrawal_Readmission
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771f98>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/policies/Laptop_ComputerUse
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771898>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/policies/Grade_Options
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9198>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/policies/Course_Outside_UCI
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157666a0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/policies/Add_Drop_ChangeOption
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157666d8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/policies/Academic_Standing
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771b70>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/policies/Academic_Honesty
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771f28>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/degrees/Minors
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156a3cf8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/degrees/index.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773e10>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/QA_Petitions
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a7f0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/courses/index-course
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115766b00>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/sao/Course_updates
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1160ac1d0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/sao/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1157666d8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115766400>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/ugrad
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771ac8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a2e8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/visit/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a0b8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/resources
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fswiki.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9ba8>: Failed to establish a new connection: [Errno 61] Connection refused')) https://swiki.ics.uci.edu/doku.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156a35c0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/funding/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9240>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/policies/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ae80>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/forms/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ad30>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/courses/index-course
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771898>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/degrees/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115766ef0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/admissions/Prospective_ApplicationProcess.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115766400>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/grad/admissions/index
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156e2f60>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/faculty/highlights
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773f98>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/faculty/centers
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115766240>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/faculty/area
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771b00>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/dept
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115771400>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/about_contact.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578a470>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/equity
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156948d0>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/visit/index.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9b00>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/brenhall/index.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115773b00>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/about_factsfigures.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1156f9e80>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about/about_deanmsg.php
<class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='styx.ics.uci.edu', port=9002): Max retries exceeded with url: /?q=https%3A%2F%2Fwww.ics.uci.edu%2Frobots.txt&u=IR+F19+38314561%2C22347485%2C17424317 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11578ad68>: Failed to establish a new connection: [Errno 61] Connection refused')) https://www.ics.uci.edu/about
